notifications:
  email: true

language: c

before_script:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - export PATH=$PATH:~/bin/

script: cd EVAL/EVAL/Debug && make BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

after_success:
  "artifacts upload  --target-paths=builds/b$TRAVIS_BUILD_NUMBER build/project-dandelion*"
